sonar.projectKey=Hussain00353_job-offer-api
sonar.organization=hussain00353
sonar.sources=analyser
sonar.tests=tests
sonar.python.version=3.9
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/venv/**,**/__pycache__/**,**/migrations/**,**/node_modules/**,**/site-packages/**,**/lambda1/**,**/lambda2/**
sonar.coverage.exclusions=**/migrations/**,**/settings.py,**/wsgi.py,**/asgi.py,**/manage.py