sonar.projectKey=Hussain00353_job-offer-api
sonar.organization=hussain00353
sonar.sources=analyser
sonar.exclusions=**/venv/**,**/__pycache__/**,**/migrations/**,**/node_modules/**,**/site-packages/**
sonar.python.version=3.9