"""
Django settings for jobofferapi project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cb!1366in2f5pz!dt2^pg&sr)x7q9ldhcc^%5oky8n%l#1w^p$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'analyser',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware',                        
    'django_permissions_policy.PermissionsPolicyMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jobofferapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jobofferapi.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'analyser' / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://2d38a09a07d34b61960283a9f9c0975d.vfs.cloud9.us-east-1.amazonaws.com',
    'https://*.elasticbeanstalk.com',
]

# environment variables 
load_dotenv(os.path.join(BASE_DIR, '.env'))

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ── Security Headers (fixing ZAP findings) ───────────
# Fix: X-Content-Type-Options Missing
SECURE_CONTENT_TYPE_NOSNIFF = True

# Fix: Cookie No HttpOnly Flag
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY    = True

# Fix: Content Security Policy (CSP) Header Not Set
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "script-src":  ("'self'", "'unsafe-inline'"),
        "style-src":   ("'self'", "'unsafe-inline'"),
        "img-src":     ("'self'", "data:"),
        "font-src":    ("'self'",),
        "connect-src": ("'self'",),
    }
}
# Fix: Cross-Origin-Embedder-Policy Header Missing
SECURE_CROSS_ORIGIN_EMBEDDER_POLICY = "require-corp"

# Fix: Cross-Origin-Resource-Policy Header Missing
SECURE_CROSS_ORIGIN_RESOURCE_POLICY = "same-site"

# Fix: Permissions Policy Header Not Set
PERMISSIONS_POLICY = {
    "geolocation":    [],
    "microphone":     [],
    "camera":         [],
    "payment":        [],
    "usb":            [],
}
