name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  # CI
  test:
    name: CI - Run Tests & Quality Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install django djangorestframework requests boto3 pytest python-dotenv pytest-cov

      - name: Run tests with coverage
        run: |
          python -m pytest tests/test_analyser.py -v --tb=short \
            --cov=analyser \
            --cov-report=xml:coverage.xml
        env:
          DJANGO_SETTINGS_MODULE: jobofferapi.settings
          PYTHONPATH: .
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.python.coverage.reportPaths=coverage.xml

  # CD: ZAP
  zap_scan:
    name: CD - ZAP Security Scan
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZAP output directory
        run: |
          mkdir -p zap-reports
          chmod 777 zap-reports
          chmod 777 .

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'http://job-offer-env.eba-svyaknhk.us-east-1.elasticbeanstalk.com'
          fail_action: false
          allow_issue_writing: false